name: Test Part
on:
  workflow_dispatch:
    inputs:
      model_id:
        description: "Test"
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        env:
          HF_TOKEN: \${{ secrets.HF_TOKEN }}
        run: |
          pip install huggingface_hub -q
          python3 -c "from huggingface_hub import HfApi; api=HfApi(token='$HF_TOKEN'); print(api.whoami())"
