name: Verify HF Email
on:
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s --max-time 15 -L -o /dev/null -w "HTTP:%{http_code} URL:%{url_effective}
"             "https://huggingface.co/email_confirmation/YHmhYVraKWOeenFfUZcXGPpkElCY"
